management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: B3
    baggage:
      enabled: true
      remote-fields:
        x-request-id
        x-b3-traceid
        x-b3-spanid
        x-b3-parentspanid
        x-b3-sampled
        x-b3-flags